[build]
  command = "npm run build"
  publish = "build"  # Se till att detta är rätt mapp, vanligtvis 'build' för React

  # Specifik Node.js-version, justera efter behov
  environment = { NODE_ENV = "production", NODE_VERSION = "16" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
