[build]
  command = "npm run build"
  publish = "build"

  # Korrekt sätt att definiera miljövariabler i TOML
  [build.environment]
    NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
